# Generated by Django 4.2.1 on 2023-05-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followed',
        ),
    ]
